id = "flang"
name = "FLang"
description = "FLang language support for Zed"
version = "0.1.2"
schema_version = 1
authors = [
    "Jo√£o Furtado <jllf.17@gmail.com>",
]
repository = "https://github.com/shadept/zed-flang"

[grammars.flang]
repository = "https://github.com/shadept/tree-sitter-flang"
rev = "c515c7084d2979e73ae4b6ea5ca9936c3177e732"

[language_servers.flang]
name = "FLang Language Server"
languages = ["FLang"]
