id = "flang"
name = "FLang"
description = "FLang language support for Zed"
version = "0.1.0"
schema_version = 1
authors = [
    "Jo√£o Furtado <jllf.17@gmail.com>",
]
repository = "https://github.com/example/flang"

[grammars.flang]
repository = "https://github.com/shadept/tree-sitter-flang"
rev = "7f9aa5badee21c6e3f05c1e47d1a3c2bd12ad8f7"

[language_servers.flang]
name = "FLang Language Server"
languages = ["FLang"]
